AY2324S2-CS2113T-T09-1/tp

docs/AboutUs.md, docs/team/wenenhoe.md
Add Wen En info to `docs/AboutUs.md` as per issue #1
=> docs: Add Wen En to `AboutUs`

docs/AboutUs.md, docs/team/linhtet.md
Add Lin Htet to AboutUs : 2426a7a
=> docs: Add Lin Htet to AboutUs

docs/AboutUs.md, docs/team/nickchua.md
Add Nick Chua to team folder and AboutUs.md
=> docs: Add Nick Chua to docs

.github/pull_request_template.md, docs/DeveloperGuide.md, docs/UserGuide.md
=> Add PR template

src/test/java/seedu/meditracker/SearchMedicationTest.java
=> Created class to test for searching medication from external database. (JUnit)

src/main/java/seedu/meditracker/DailyMedication.java, src/main/java/seedu/meditracker/DailyMedicationManager.java, src/test/java/seedu/meditracker/DailyMedicationManagerTest.java
=> feat: Mark medication taken

src/test/java/meditracker/QuerySpecificMedication.java
Closes None of the issues
- User Guide
Closes None of the issues
This is just to test the JUnit.
=> chore: Add JUnit Test for QuerySpecificMedicineCommand

build.gradle, docs/team/songxuan.md, src/test/java/meditracker/DummyTest.java
Closes #26
Relevant import statement: `import org.json.*`
Permitted based on (https://github.com/nus-cs2113-AY2324S2/forum/issues/16)
(Also add fake test to satisfy course requirements)
=> chore: bring in JSON dependency

src/main/java/meditracker/DailyMedication.java, src/main/java/meditracker/DailyMedicationManager.java, src/main/java/meditracker/command/ListTodayCommand.java, src/main/java/meditracker/ui/Ui.java, src/test/java/meditracker/ui/UiTest.java
Printing the daily medication list will include the status and the medication name in each line
- User Guide
Nil
=> feat: Print list of medications to take for the day

src/main/java/meditracker/command/DeleteCommand.java, src/main/java/meditracker/medication/MedicationManager.java, src/main/java/meditracker/parser/Parser.java, src/main/java/meditracker/ui/Ui.java, src/test/java/meditracker/command/DeleteCommandTest.java, text-ui-test/EXPECTED.TXT, text-ui-test/input.txt
=> feat: Delete medication

docs/DeveloperGuide.md, docs/team/songxuan.md, src/main/java/meditracker/exception/FileReadWriteException.java, src/main/java/meditracker/storage/FileReaderWriter.java
=> Feat default save file

src/main/java/meditracker/DailyMedicationManager.java
Closes #50
- User Guide
Closes #50
Parses and saves each lines loaded from textfile into DailyMedicationManager
=> Parses and saves each lines loaded from textfile

src/main/java/meditracker/DailyMedicationManager.java, src/main/java/meditracker/medication/MedicationManager.java, src/test/java/meditracker/DailyMedicationManagerTest.java
Closes #52
- User Guide
Closes #52
Nil
=> Add medication info into daily

src/main/java/meditracker/command/ModifyCommand.java
=> fix(bug): Edit iterator in for loop

src/main/java/meditracker/DailyMedication.java, src/main/java/meditracker/command/ModifyCommand.java, src/test/java/meditracker/command/ModifyCommandTest.java
=> fix(bug): Update daily medication name on modify

src/main/java/meditracker/command/AddCommand.java
=> chore: Add assertion to Add command

build.gradle, src/main/java/meditracker/DailyMedicationManager.java
Closes #69
- User Guide
Closes #69
Nil
=> Save to file

src/main/java/meditracker/DailyMedicationManager.java, src/main/java/meditracker/medication/MedicationManager.java, src/main/java/meditracker/ui/Ui.java, src/test/java/meditracker/ui/UiTest.java
Closes #79
- User Guide
Closes #79
Nil
=> Instantiate UI

src/main/java/meditracker/DailyMedicationManager.java, src/main/java/meditracker/MediTracker.java, src/main/java/meditracker/command/AddCommand.java, src/main/java/meditracker/command/Command.java, src/main/java/meditracker/command/DeleteCommand.java, src/main/java/meditracker/command/ExitCommand.java, src/main/java/meditracker/command/ListCommand.java, src/main/java/meditracker/command/ModifyCommand.java, src/main/java/meditracker/command/SearchCommand.java, src/main/java/meditracker/command/TakeCommand.java, src/main/java/meditracker/command/UntakeCommand.java, src/test/java/meditracker/AddCommandTest.java, src/test/java/meditracker/DailyMedicationManagerTest.java, src/test/java/meditracker/command/DeleteCommandTest.java, src/test/java/meditracker/command/ModifyCommandTest.java, src/test/java/meditracker/command/TakeCommandTest.java, src/test/java/meditracker/command/UntakeCommandTest.java
Closes #81
- User Guide
Closes #81
Nil
=> Modify daily to static

docs/DeveloperGuide.md, docs/team/ericsimchongli.md, src/main/java/meditracker/command/AddCommand.java, src/main/java/meditracker/command/ListCommand.java, src/main/java/meditracker/medication/Medication.java, src/main/java/meditracker/medication/MedicationManager.java, src/main/java/meditracker/ui/Ui.java, src/test/java/meditracker/command/ListCommandTest.java, text-ui-test/EXPECTED.TXT, text-ui-test/input.txt
Closes NIL
- User Guide
Closes NIL
=> Update list all medication

docs/DeveloperGuide.md, docs/team/linhtet.md
=> DG: Adds DG from Lin Htet

docs/DeveloperGuide.md
=> DG: Add DG by kyuichyi

.gitignore, src/main/java/meditracker/MediTracker.java, src/main/java/meditracker/command/AddCommand.java, src/main/java/meditracker/command/Command.java, src/main/java/meditracker/command/DeleteCommand.java, src/main/java/meditracker/command/ExitCommand.java, src/main/java/meditracker/command/ListCommand.java, src/main/java/meditracker/command/ModifyCommand.java, src/main/java/meditracker/command/SearchCommand.java, src/main/java/meditracker/command/TakeCommand.java, src/main/java/meditracker/command/UntakeCommand.java, src/main/java/meditracker/dailymedication/DailyMedicationManager.java, src/main/java/meditracker/medication/MedicationManager.java, src/main/java/meditracker/storage/FileReaderWriter.java, src/main/java/meditracker/storage/JsonExporter.java, src/main/java/meditracker/storage/JsonImporter.java, src/test/java/meditracker/AddCommandTest.java, src/test/java/meditracker/DailyMedicationManagerTest.java, src/test/java/meditracker/command/DeleteCommandTest.java, src/test/java/meditracker/command/ListCommandTest.java, src/test/java/meditracker/command/ModifyCommandTest.java, src/test/java/meditracker/command/TakeCommandTest.java, src/test/java/meditracker/command/UntakeCommandTest.java, src/test/java/meditracker/storage/JsonExporterTest.java
Closes #92
- User Guide
Closes #92
Nil
=> Update medication manager to static

src/main/java/meditracker/command/AddCommand.java
=> refactor: Refactor assertionTest function

src/main/java/meditracker/MediTracker.java, src/main/java/meditracker/argument/RepeatArgument.java, src/main/java/meditracker/command/AddCommand.java, src/main/java/meditracker/command/Command.java, src/main/java/meditracker/dailymedication/DailyMedicationManager.java, src/test/java/meditracker/AddCommandTest.java, src/test/java/meditracker/DailyMedicationManagerTest.java
Fixes #105 and fixes #110 
- User Guide
Closes #105 and closes #110 
Nil
=> Obj for each sub list

docs/team/songxuan.md, src/main/java/meditracker/MediTrackerConfig.java, src/main/java/meditracker/storage/FileReaderWriter.java
Closes #121 
Build on the commits on / To be reviewed after #117 is closed
=> Refactor change dailymedication save file

src/main/java/meditracker/argument/AfternoonArgument.java, src/main/java/meditracker/argument/AllFieldsArgument.java, src/main/java/meditracker/argument/Argument.java, src/main/java/meditracker/argument/DosageAfternoonArgument.java, src/main/java/meditracker/argument/DosageEveningArgument.java, src/main/java/meditracker/argument/DosageMorningArgument.java, src/main/java/meditracker/argument/EveningArgument.java, src/main/java/meditracker/argument/ExpirationDateArgument.java, src/main/java/meditracker/argument/HelpArgument.java, src/main/java/meditracker/argument/IllnessArgument.java, src/main/java/meditracker/argument/ListIndexArgument.java, src/main/java/meditracker/argument/ListTypeArgument.java, src/main/java/meditracker/argument/LoadArgument.java, src/main/java/meditracker/argument/MorningArgument.java, src/main/java/meditracker/argument/NameArgument.java, src/main/java/meditracker/argument/QuantityArgument.java, src/main/java/meditracker/argument/RemarksArgument.java, src/main/java/meditracker/argument/RepeatArgument.java, src/main/java/meditracker/argument/SaveArgument.java, src/main/java/meditracker/argument/SideEffectsArgument.java, src/test/java/meditracker/argument/ArgumentListTest.java
=> refactor: Remove prompt from `Argument` classes

src/main/java/meditracker/command/AddCommand.java, src/main/java/meditracker/command/ModifyCommand.java, src/main/java/meditracker/medication/Medication.java
=> fix(bug): ModifyCommand handle erroneous data and fix AddCommand error handling

docs/UserGuide.md, docs/team/wenenhoe.md
=> docs: Add user guide for commands

docs/UserGuide.md, text-ui-test/data/dailymed/today.txt
=> docs: Update UG for Add command

docs/UserGuide.md
=> docs(UserGuide): update search command section

docs/team/wenenhoe.md, src/main/java/meditracker/command/Command.java, src/main/java/meditracker/command/DeleteCommand.java, src/main/java/meditracker/command/ModifyCommand.java, src/main/java/meditracker/command/TakeCommand.java, src/main/java/meditracker/command/UntakeCommand.java, src/test/java/meditracker/command/DeleteCommandTest.java, src/test/java/meditracker/command/ModifyCommandTest.java, src/test/java/meditracker/command/TakeCommandTest.java, src/test/java/meditracker/command/UntakeCommandTest.java
`modify`: Fixes #154, fixes #155, fixes #179
`delete`: Fixes #194, fixes #204 
`take`: Fixes #156, fixes #195 
- User Guide
- Refactor obtaining list index and period to static methods in `Command` class
=> fix(bug): Fix number format exception for `modify`, `delete`, `take`, `untake`

docs/team/wenenhoe.md, src/main/java/meditracker/argument/ArgumentParser.java, src/main/java/meditracker/argument/RepeatArgument.java, src/main/java/meditracker/command/DeleteCommand.java, src/main/java/meditracker/command/ModifyCommand.java, src/main/java/meditracker/command/TakeCommand.java, src/main/java/meditracker/command/UntakeCommand.java, src/main/java/meditracker/dailymedication/DailyMedicationManager.java, src/main/java/meditracker/exception/MedicationUnchangedException.java, src/main/java/meditracker/medication/Medication.java, src/main/java/meditracker/medication/MedicationManager.java, src/main/java/meditracker/ui/Ui.java, src/test/java/meditracker/dailymedication/DailyMedicationManagerTest.java, text-ui-test/EXPECTED.TXT, text-ui-test/input.txt
Fixes #178
- User Guide
- Refactor checking if medication has dosage for day Period into method in `Medication`
=> fix(bug): Show no change to quantity

docs/DeveloperGuide.md, docs/team/annoy-o-mus.md
=> docs: Update Dev Guide based on comments

docs/team/wenenhoe.md, src/main/java/meditracker/command/AddCommand.java, src/main/java/meditracker/command/Command.java, src/main/java/meditracker/command/ModifyCommand.java, src/main/java/meditracker/medication/Medication.java, text-ui-test/EXPECTED.TXT, text-ui-test/input.txt
=> fix(bug): Fix modify command behaviour

docs/UserGuide.md, docs/team/wenenhoe.md, src/main/java/meditracker/command/ModifyCommand.java
Closes #189
- Preview of User Guide is available [here](https://wenenhoe.github.io/tp/UserGuide.html)
- To export to PDF, use Chrome and also set the scaling to 80% as shown [here](https://volstate.teamdynamix.com/TDClient/1994/Portal/KB/ArticleDet?ID=62402)
=> docs: Fix up docs and add more info for modify

src/test/java/meditracker/storage/JsonExporterTest.java
=> [#146] style: fix style

src/main/java/meditracker/command/ListCommand.java, src/main/java/meditracker/command/ViewCommand.java, src/main/java/meditracker/medication/Medication.java, src/main/java/meditracker/medication/MedicationManager.java, src/test/java/meditracker/command/ListCommandTest.java, src/test/java/meditracker/command/ViewCommandTest.java, src/test/java/meditracker/medication/MedicationManagerTest.java
Closes #148 
Closes #148 
Fixes styles in the following files:
1. [ListCommand](https://github.com/AY2324S2-CS2113T-T09-1/tp/commit/5d71af19756fa233be8f21503f31ce694d65f72a)
2. [ListCommandTest](https://github.com/AY2324S2-CS2113T-T09-1/tp/commit/2a471b1b26ca887928879897e8daa9810b2b6ed2)
ListCommandTest checks is intended to have some failing checks as the methods authored by @T0nyLin 
3. [ViewCommand](https://github.com/AY2324S2-CS2113T-T09-1/tp/commit/86852fa9d212994ab0ce57f9b409374c3155f0cf)
4. [ViewCommandTest](https://github.com/AY2324S2-CS2113T-T09-1/tp/commit/ed8d7a68854d4c6f8fa407676b2fc3bf9492948d)
5. [MedicationManagerTest](https://github.com/AY2324S2-CS2113T-T09-1/tp/commit/51ca5e5e0ddea309673823b515d3191beeea9fd4)
6. …
=> [#148] style: fix style - Eric

docs/team/t0nylin.md
=> Updates PPP
